# Generated by Django 4.2.17 on 2026-01-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='bomb',
            new_name='trophy',
        ),
    ]
