# Generated by Django 4.2.17 on 2026-02-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper_api', '0002_rename_bomb_cell_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameMode',
            field=models.CharField(choices=[('Octagon-Square', 'Octagon Square'), ('Square', 'Square'), ('Triangle', 'Triangle'), ('Square-Triangle', 'Square Triangle'), ('Hexagon-Square-Triangle', 'Hexagon Square Triangle')], default='Octagon-Square', max_length=25),
        ),
    ]
