# Generated by Django 4.2.17 on 2025-01-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField(default=11)),
                ('row', models.IntegerField(default=21)),
                ('key', models.IntegerField(default=-1)),
                ('outofBounds', models.BooleanField(default=False)),
                ('mine', models.BooleanField(default=False)),
                ('revealed', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('adjacent', models.IntegerField(default=0)),
                ('startingPoint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_ID', models.IntegerField()),
                ('progress', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('WIN', 'Win'), ('LOST', 'Lost')], default='NS', max_length=5)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Extreme', 'Extreme'), ('Impossible', 'Impossible')], default='Easy', max_length=20)),
                ('sideLength', models.IntegerField()),
                ('rows', models.IntegerField(default=11)),
                ('columns', models.IntegerField(default=21)),
                ('numCells', models.IntegerField(default=91)),
                ('mines', models.IntegerField(default=18)),
                ('flags', models.IntegerField(default=18)),
                ('numberRevealed', models.IntegerField()),
                ('mine_keys', models.JSONField(default=list)),
                ('board', models.ManyToManyField(to='beesweeper_api.cell')),
            ],
        ),
    ]
