# Generated by Django 4.2.17 on 2025-01-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesweeper_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='key_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='reverse_key_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='numberRevealed',
            field=models.IntegerField(default=73),
        ),
        migrations.AlterField(
            model_name='game',
            name='sideLength',
            field=models.IntegerField(default=6),
        ),
    ]
