# Generated by Django 4.2.17 on 2025-08-28 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beesweeper_api', '0002_game_key_map_game_reverse_key_map_alter_game_game_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
