# Generated by Django 4.2.17 on 2025-08-28 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beesweeper_api', '0003_remove_game_id_alter_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
