# Generated by Django 4.2.17 on 2025-08-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beesweeper_api', '0004_alter_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='honey',
            field=models.BooleanField(default=False),
        ),
    ]
