# Generated by Django 4.2.17 on 2025-01-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('code', models.IntegerField()),
                ('outOfBounds', models.BooleanField()),
                ('mine', models.BooleanField()),
                ('startingPoint', models.BooleanField()),
                ('adjacent', models.IntegerField()),
                ('revealed', models.BooleanField()),
                ('visited', models.BooleanField()),
                ('flagged', models.BooleanField()),
                ('top', models.BooleanField()),
                ('topRight', models.BooleanField()),
                ('bottomRight', models.BooleanField()),
                ('bottom', models.BooleanField()),
                ('bottomLeft', models.BooleanField()),
                ('topLeft', models.BooleanField()),
            ],
        ),
    ]
